[package]
name = "framecraft-desktop"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "2", features = [] }
cc = "1"

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dunce = "1.0.5"
ash = "0.38"
ash-window = "0.13"
raw-window-handle = "0.6"
tokio = { version = "1", features = ["sync"] }
reqwest = { version = "0.13", default-features = false, features = ["json"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
gdk = "0.18"
glib = "0.18"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_System_LibraryLoader"] }

[profile.dev]
debug = 0
incremental = false

[profile.release]
strip = true
lto = "thin"
