import {test, expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {mkdir, realpath, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {clipSchema, type Snapshot} from '../../shared/project';

test('resizable editing workflow retains full-resolution playback and source-matched export', async ({page, request}) => {
  await page.setViewportSize({width: 1280, height: 720});
  const snapshot = async (): Promise<Snapshot> => (await request.get('/api/project')).json();
  const original = await snapshot();
  const created = await request.post('/api/projects', {data: {action: 'new', name: 'Gameplay · Build 014', revision: original.project.revision, settings: {width: 1280, height: 720, fps: 24}}});
  expect(created.ok()).toBe(true);
  const directory = path.resolve('test-results/workspace-quality'); await mkdir(directory, {recursive: true});
  const source = path.join(directory, 'Gameplay capture.avi');
  execFileSync(process.env.FFMPEG_PATH || 'ffmpeg', ['-y', '-f', 'lavfi', '-i', 'testsrc2=s=1536x864:r=12:d=1', '-c:v', 'mpeg4', '-q:v', '3', source], {stdio: 'ignore'});
  const imported = await request.post('/api/import-path', {data: {filePath: source}}); expect(imported.ok()).toBe(true);
  const current = await snapshot(); const asset = current.project.assets[0];
  expect(asset).toMatchObject({width: 1536, height: 864, fps: 12});
  const caches = await (await request.get('/api/media/previews')).json();
  expect(caches[`${asset.id}:high`].status).toBe('idle');
  expect(['queued', 'running', 'ready']).toContain(caches[asset.id].status);
  expect(current.project.clips).toHaveLength(0);
  await expect.poll(async () => (await (await request.get('/api/media/previews')).json())[asset.id].status, {timeout: 20000}).toBe('ready');
  const added = await request.post('/api/commands', {data: {revision: current.project.revision, commands: [
    {type: 'clip.add', clip: clipSchema.parse({id: 'quality-video', name: 'Gameplay capture', assetId: asset.id, kind: 'video', track: 'visual', start: 0, duration: 24})},
    {type: 'clip.add', clip: clipSchema.parse({id: 'quality-title', name: 'Chapter title', kind: 'text', track: 'text', start: 0, duration: 24, text: 'BUILD 014 / GAMEPLAY', fontSize: 44, y: 75, animation: 'none'})},
  ]}}); expect(added.ok()).toBe(true);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const video = page.locator('.preview__canvas video');
  await expect.poll(() => video.evaluate((element: HTMLVideoElement) => element.readyState >= 2 && element.videoWidth), {timeout: 30000}).toBe(1536);
  await expect(video).toHaveAttribute('src', /preview-full-v1\.mp4/);
  await expect(page.locator('.preview__source-quality')).toContainText('1536 × 864');
  expect((await snapshot()).project.revision).toBe((await added.json()).project.revision);
  await page.getByRole('combobox', {name: 'Playback quality'}).selectOption('proxy-360');
  await expect(video).toHaveAttribute('src', /preview-360p-intra-v1\.mp4/, {timeout: 30000});
  await expect.poll(() => video.evaluate((element: HTMLVideoElement) => element.readyState >= 2 && element.videoWidth)).toBe(640);
  const proxyState = (await (await request.get('/api/media/previews')).json())[`${asset.id}:proxy-360`];
  const proxyFile = path.join(directory, 'editing-proxy.mp4');
  await writeFile(proxyFile, await (await request.get(proxyState.src)).body());
  const proxyProbe = JSON.parse(execFileSync(process.env.FFPROBE_PATH || 'ffprobe', ['-v', 'error', '-select_streams', 'v:0', '-show_frames', '-show_entries', 'frame=key_frame,pict_type,best_effort_timestamp_time', '-of', 'json', proxyFile], {encoding: 'utf8'}));
  expect(proxyProbe.frames).toHaveLength(12);
  expect(proxyProbe.frames.every((frame: {key_frame: number; pict_type: string}) => frame.key_frame === 1 && frame.pict_type === 'I')).toBe(true);
  expect(Number(proxyProbe.frames[11].best_effort_timestamp_time)).toBeCloseTo(11 / 12, 5);
  await page.reload();
  await expect(page.getByRole('combobox', {name: 'Playback quality'})).toHaveValue('proxy-360');
  await expect.poll(() => video.getAttribute('src').then(src => src?.split('#')[0])).toBe(proxyState.src);
  expect((await snapshot()).project.assets[0].src).toBe(asset.src);
  const fullWidth = (await page.locator('.preview').boundingBox())!.width;
  await expect(page.getByRole('button', {name: 'Review', exact: true})).toHaveCount(0);
  await expect(page.getByRole('button', {name: 'AI edit', exact: true})).toHaveCount(0);
  await page.getByRole('button', {name: 'Toggle media panel', exact: true}).click();
  await page.getByRole('button', {name: 'Toggle properties and Codex panel', exact: true}).click();
  await expect.poll(async () => (await page.locator('.preview').boundingBox())!.width).toBeGreaterThan(fullWidth + 300);
  await page.getByRole('button', {name: 'Edit', exact: true}).click();
  const handle = page.getByRole('separator', {name: 'Resize media panel'}); const handleBox = (await handle.boundingBox())!;
  await page.mouse.move(handleBox.x + 3, handleBox.y + 50); await page.mouse.down(); await page.mouse.move(handleBox.x + 33, handleBox.y + 50); await page.mouse.up();
  await expect(handle).toHaveAttribute('aria-valuenow', '350');
  await page.getByRole('button', {name: 'Reset workspace layout'}).click();
  await page.locator('[data-clip-id="quality-title"]').click({button: 'right'});
  await expect(page.getByRole('menu', {name: 'Clip actions'})).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('menu', {name: 'Clip actions'})).toHaveCount(0);
  await page.getByRole('button', {name: 'Snap clips (N)'}).click();
  await expect(page.getByRole('button', {name: 'Snap clips (N)'})).toHaveAttribute('aria-pressed', 'false');
  await page.keyboard.press('n');
  await expect(page.getByRole('button', {name: 'Snap clips (N)'})).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', {name: 'Go to beginning', exact: true}).click();
  await page.getByRole('button', {name: `Preview ${asset.name}`, exact: true}).click();
  await expect(page.getByRole('dialog', {name: asset.name})).toBeVisible();
  await page.getByRole('button', {name: 'Insert at playhead', exact: true}).click();
  await expect.poll(async () => (await snapshot()).project.clips.length).toBe(3);
  await page.getByRole('button', {name: `Close ${asset.name.toLowerCase()}`, exact: true}).click();
  await page.getByRole('button', {name: 'Undo timeline edit (Ctrl+Z)', exact: true}).click();
  await expect.poll(async () => (await snapshot()).project.clips.length).toBe(2);
  expect((await snapshot()).project.clips).toHaveLength(2);
  await page.locator('[data-clip-id="quality-title"]').click();
  await page.screenshot({path: path.join(directory, 'editor-1280.png')});
  expect(await page.locator('.editor-layout').evaluate(element => element.getBoundingClientRect().right <= innerWidth && element.getBoundingClientRect().bottom <= innerHeight)).toBe(true);
  await page.getByRole('button', {name: 'Export video', exact: true}).click();
  const dialog = page.getByRole('dialog', {name: 'Export settings'});
  await expect(dialog.getByRole('textbox', {name: 'Export file path'})).toHaveValue(/[\\/]projects[\\/][a-f0-9]{64}[\\/]exported[\\/].+\.mp4$/);
  const chosenOutput = path.join(directory, `custom export ${Date.now()}.mp4`);
  await dialog.getByRole('textbox', {name: 'Export file path'}).fill(chosenOutput);
  await dialog.getByRole('button', {name: 'Match source', exact: true}).click();
  await expect(dialog.getByRole('spinbutton', {name: 'Width (px)', exact: true})).toHaveValue('1536');
  await expect(dialog.getByRole('spinbutton', {name: 'Frame rate (fps)', exact: true})).toHaveValue('12');
  await expect(dialog.getByRole('spinbutton', {name: 'CRF', exact: true})).toHaveValue('16');
  await dialog.getByRole('combobox', {name: 'Video encoder', exact: true}).selectOption('cpu');
  await dialog.locator('summary').filter({hasText: 'Export range'}).click();
  await dialog.getByRole('spinbutton', {name: 'Export end (seconds)', exact: true}).fill('0.5');
  const jobResponse = page.waitForResponse(response => response.url().endsWith('/api/render') && response.request().method() === 'POST');
  await dialog.getByRole('button', {name: 'Export now', exact: true}).click();
  const job = await (await jobResponse).json();
  await expect.poll(async () => (await (await request.get(`/api/render/${job.id}`)).json()).status, {timeout: 90000}).toMatch(/done|error/);
  const done = await (await request.get(`/api/render/${job.id}`)).json(); expect(done.status, done.error).toBe('done');
  expect(done.outputPath).toBe(chosenOutput);
  expect((await (await request.get(`/api/render/${job.id}/output`)).json()).path).toBe(await realpath(chosenOutput));
  const output = path.join(directory, 'quality-export.mp4'); await writeFile(output, await (await request.get(done.url)).body());
  const probe = JSON.parse(execFileSync(process.env.FFPROBE_PATH || 'ffprobe', ['-v', 'error', '-count_frames', '-select_streams', 'v:0', '-show_entries', 'stream=width,height,nb_read_frames,r_frame_rate', '-of', 'json', output], {encoding: 'utf8'}));
  expect(probe.streams[0]).toMatchObject({width: 1536, height: 864, r_frame_rate: '12/1', nb_read_frames: '6'});
  expect(errors).toEqual([]);
});
