import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import {z} from 'zod';
import {commandSchema, type RenderJob, type Snapshot} from '../shared/project';
import {McpPresenceService} from './services/mcp-presence-service';
import {codecNames, exportSettingsSchema} from '../shared/media-settings';
import {captionOptionsSchema} from '../shared/assisted-editing';
import {transcriptWordSchema} from '../shared/transcript';
import {presetApplySchema, presetPreviewSchema, presetSaveSchema, type SavedPreset} from '../shared/asset-presets';
import {projectActionSchema} from '../shared/project-library';
import {analyzeVideoSchema, applyVideoCutSchema, inspectVideoSchema, saveVideoCutSchema, type VideoSheet} from '../shared/visual-rush';
import {timelineRangeRequestSchema} from '../shared/timeline-range-request';
import {audioDuckSchema} from '../shared/audio-mix';
import {applyAudioEffectsSchema} from '../shared/audio-effects';
import {soundApplySchema, soundPreviewSchema, soundSaveSchema} from '../shared/sound-presets';
import {colorGradeRequestSchema} from '../shared/color-grade-editing';
import {visualStateAtFrame} from '../shared/visual-editing';
import {applySpeedSchema, resetSpeedSchema} from '../shared/speed-ramping';
import {timelineExportSchema} from '../shared/timeline-interchange';

const base = process.env.FRAMECRAFT_URL || 'http://127.0.0.1:4318';
const server = new McpServer({name: 'framecraft', version: '0.1.0'});
const presence = new McpPresenceService(base);
server.server.oninitialized = () => presence.start(server.server.getClientVersion()?.name || 'Codex');
server.server.onclose = () => {void presence.stop();};
const close = async () => {await presence.stop(); await server.close();};
process.once('SIGTERM', () => {void close();});
process.once('SIGINT', () => {void close();});
process.stdin.once('end', () => {void close();});
async function api(route: string, body?: unknown) {
  let response: Response;
  try {response = await fetch(base + route, {method: body === undefined ? 'GET' : 'POST', headers: {'Content-Type': 'application/json', 'X-Framecraft-Client': 'codex'}, ...(body === undefined ? {} : {body: JSON.stringify(body)})});}
  catch(error) {throw new Error(`Cannot reach the Framecraft editor at ${base}. Run "npm run dev" in the Framecraft folder and keep that terminal open, then retry this tool. ${(error as Error).message}`);}
  const result = await response.json(); if(!response.ok) throw new Error(result.error || response.statusText); return result;
}
const textResult = (value: unknown) => ({content: [{type: 'text' as const, text: JSON.stringify(value, null, 2)}]});
server.registerTool('analyze_video', {description: 'Scan a video without requiring speech. Runs real local FFmpeg analysis of luminance and frame differences and saves a visual map with up to 48 representative moments across the whole source. Low motion, darkness and large visual changes are inspection cues, NOT proof of boredom, menus, wins or failures. Cached reports are reused unless refresh=true. Returns an analysis job; poll get_analysis, then get_video_analysis with its reportId. Use inspect_video to SEE the footage before deciding cuts.', inputSchema: analyzeVideoSchema.shape}, async input => textResult(await api('/api/visual-rush/analyze', input)));
server.registerTool('get_video_analysis', {description: 'Read a visual report by reportId, or list reports and saved video cut proposals for the current project. Report times, cue ranges and cut proposal start/end values are SOURCE SECONDS. The overview samples the entire duration but can miss brief events; inspect relevant/ambiguous ranges at finer intervals.', inputSchema: {reportId: z.string().uuid().optional()}}, async ({reportId}) => textResult(await api(`/api/visual-rush${reportId ? `/reports/${reportId}` : ''}`)));
server.registerTool('inspect_video', {description: 'SEE actual imported source footage, independent of the timeline. Provide reportId and either page (zero-based, 12 overview frames per page), start/end (source seconds, 12-frame sampling batches), or time (one larger 1280px frame for details). Returns a JPEG with a precise frame index/timestamp map. Grids read left-to-right, top-to-bottom; unused cells are black, not source footage. For temporal action inspect short ranges, and inspect boundaries before deciding cuts. Reuse cached images. Read all overview pages for coverage before claiming to review a whole source; do not infer events from motion scores alone.', inputSchema: {inspection: inspectVideoSchema}}, async ({inspection}) => {
  const sheet: VideoSheet = await api('/api/visual-rush/inspect', inspection); const response = await fetch(base + sheet.url); if(!response.ok) throw new Error('Could not retrieve source frames');
  return {content: [{type: 'text' as const, text: JSON.stringify(sheet)}, {type: 'image' as const, data: Buffer.from(await response.arrayBuffer()).toString('base64'), mimeType: 'image/jpeg'}]};
});
server.registerTool('save_video_cut', {description: 'Save a reviewable visual cut proposal in Tools → Automatic Cuts, without modifying the timeline. Read get_project for revision. Provide reportId, title, goal, and ordered shots with unique id, start/end in SOURCE SECONDS, concrete visual reason, confidence=high|medium|low, and evidence array of exact timestamps returned by inspect_video inside that shot. There is no count limit on evidence timestamps, shots, or selected shot IDs, and no length cap on proposal descriptions. Keep all useful evidence. Previously inspected frames remain valid across restarts while their image cache exists. Preserve setup/action/payoff and avoid repeated footage; uncertainty must be stated honestly. No semantic detections are supplied by the local scan. New proposal: omit id, expectedVersion=null. Updating: pass id and current expectedVersion.', inputSchema: saveVideoCutSchema.shape}, async input => textResult(await api('/api/visual-rush/cuts', input)));
server.registerTool('apply_video_cut', {description: 'Apply any number of shots from a saved video cut as ONE undoable edit. Requires current project revision and proposal version. mode=append appends to a video track; mode=replace-track replaces only that track, leaving other tracks at their existing times. Optional trackId chooses a video track; shotIds selects/reorders distinct proposal shots. Source seconds convert to the current project fps. Original media stay intact. Apply only when the user has requested applying the cut.', inputSchema: applyVideoCutSchema.shape}, async input => textResult(await api('/api/visual-rush/apply', input)));
server.registerTool('list_projects', {description: 'List saved projects and the active project ID, with names, canvas settings, media/clip counts and saved dates. Project edits autosave; reusable asset presets are shared.', inputSchema: {}}, async () => textResult(await api('/api/projects')));
server.registerTool('manage_project', {description: 'Create a blank project (action=new, name, settings), save an independent copy and open it (action=copy, name), or open a saved project (action=open, id). Pass the current revision from get_project. The outgoing project and its undo history are saved. After switching, reread get_project and use its new revision; do not reuse the previous project selection or commands. Only switch projects when requested by the user.', inputSchema: {operation: projectActionSchema}}, async ({operation}) => textResult(await api('/api/projects', operation)));
server.registerTool('list_asset_presets', {description: 'List the persistent reusable asset library. Pass id to read one complete recipe before editing/applying it. Recipes use normalized layer coordinates (percent), numeric keyframes at progress 0..1, and typed parameter references {param:key}. No code generation or restart is required. Presets are shared across projects; timeline instances embed their version.', inputSchema: {id: z.string().optional(), query: z.string().max(100).optional()}}, async ({id, query}) => {
  if(id) return textResult(await api(`/api/asset-presets/${encodeURIComponent(id)}`));
  const catalog = await api('/api/asset-presets');
  return textResult({revision: catalog.revision, presets: (catalog.presets as SavedPreset[]).filter(p => !query || `${p.definition.name} ${p.definition.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).map(p => ({id: p.id, version: p.version, name: p.definition.name, category: p.definition.category, description: p.definition.description, parameters: p.definition.parameters, duration: p.definition.duration}))});
});
server.registerTool('save_asset_preset', {description: 'Create a reusable animation/transition asset or save a new version. Omit id and use expectedVersion=null for a new preset; updating requires its exact version. Define rect/ellipse/text layers with x/y/width/height in percent, fontSize/strokeWidth in percent of canvas height. Scalars accept a number, numeric parameter reference, or ordered keyframes. Colors and text accept matching parameter references. Transition recipes also require reveal fade/wipe/iris/blocks and can layer animated shapes over the reveal. Saved assets appear live in Asset Studio; existing timeline instances are unchanged. Use preview_asset_preset to inspect the result.', inputSchema: presetSaveSchema.shape}, async input => textResult(await api('/api/asset-presets/save', input)));
server.registerTool('apply_asset_preset', {description: 'Apply a saved asset as one undoable project edit. Pass current project revision and preset version. Graphics are inserted at frame; optional trackId chooses a video or text track. Transitions apply to the incoming visual clipId. values overrides exposed parameters and duration sets seconds. Each instance embeds its complete recipe, so later library edits/deletion cannot change it.', inputSchema: presetApplySchema.shape}, async input => textResult(await api('/api/asset-presets/apply', input)));
server.registerTool('preview_asset_preset', {description: 'Render an isolated preset preview without changing the timeline. Default kind=frame returns an actual PNG at progress 0..1; kind=video queues an animated MP4 preview. Transitions use two sample scenes. Poll get_render if still queued.', inputSchema: presetPreviewSchema.shape}, async input => {
  let job: RenderJob = await api('/api/asset-presets/preview', input);
  if(input.kind !== 'video') {const deadline = Date.now() + 45000; while(Date.now() < deadline && ['queued', 'rendering'].includes(job.status)) {await new Promise(resolve => setTimeout(resolve, 700)); job = await api(`/api/render/${job.id}`);}}
  return renderResult(job);
});
server.registerTool('get_project', {description: 'Read the current project, assets, clips, revision, undo state, recent edits, and editor selection/playhead. Includes ordered tracks (top first), clip.trackId and position locks. All timeline times are integer frames at the current project fps. Call before editing.', inputSchema: {}}, async () => textResult({...(await api('/api/project')), context: await api('/api/status')}));
server.registerTool('set_color_grade', {description: 'Grade imported video/image footage with exposure (stops), contrast, saturation, temperature, tint, gamma and hue. scope=timeline without ranges sets the global grade; clips+clipIds or tracks+trackIds targets their current clips. Optional ranges are original TIMELINE FRAMES [start,end): only intersecting portions are graded, splitting visual clips without shifting content. Range boundaries inside entrance transitions are rejected; grade the whole clip or start after the transition. Partial grade fields merge with current values; grade=null resets the chosen grade. Clip grade runs before the project grade; text/graphic artwork is not graded. apply=false returns an edit plan, apply=true commits one undo step at the given revision. Use render_frame before/after to SEE colors; original media remain unchanged. Controls are numeric grades, not masks, tracked qualifiers, external LUT import or automatic shot matching.', inputSchema: colorGradeRequestSchema.shape}, async input => textResult(await api('/api/color-grading', input)));
server.registerTool('edit_timeline_ranges', {description: 'Cut or rearrange an EXISTING multi-track timeline, preserving synchronization across participating video, audio, captions and graphics. Ranges use original TIMELINE FRAMES [start,end), not source seconds. operation=remove merges ranges and ripples the remainder; assemble keeps ranges in the supplied order from frame 0, including repeated sections. Default affects ALL tracks; optional trackIds leaves other tracks fixed. apply=false previews counts, duration and warnings; apply=true commits ONE undo step at the supplied revision. Inspect the resulting composite frames. Does not detect gameplay events or synchronize misaligned recordings.', inputSchema: timelineRangeRequestSchema.shape}, async input => textResult(await api('/api/timeline/ranges', input)));
server.registerTool('duck_audio', {description: 'Generate editable music/background volume keyframes beneath clips on chosen foreground tracks. Uses TIMELINE CLIP SPANS, not detected speech/loudness. gain is the remaining volume multiplier 0..1; attackFrames/releaseFrames are project frames. Excludes muted tracks and target clips from triggers. Replaces target fades and automation. apply=false returns the exact commands for review; apply=true commits one undo step. For manual fades/automation use clip.update.audioEnvelope through edit_project: duration/offset/fadeIn/fadeOut and ordered keyframes {frame,value}, all in project frames.', inputSchema: audioDuckSchema.shape}, async input => textResult(await api('/api/audio/duck', input)));
server.registerTool('apply_audio_effects', {description: 'Process selected video/audio clip sound with 3-band EQ (dB), compression and/or a multi-tap room reverb. Queues local bounded FFmpeg work; poll get_audio_effect_job. Produces project-owned audio copies shared by preview/export, preserving originals. Video clips receive separate processed audio clips and their original sound is muted. Reprocessing generated audio uses its retained original. Reverb tails are trimmed to clip duration to keep timing. Timeline changes during processing abort the commit rather than overwrite edits. Applied result is one undo step.', inputSchema: applyAudioEffectsSchema.shape}, async input => textResult(await api('/api/audio-effects/apply', input)));
server.registerTool('get_audio_effect_job', {description: 'Read actual audio effect processing status, progress, resulting clip IDs or errors. cancel=true cancels pending/running work without applying a timeline edit.', inputSchema: {id: z.string(), cancel: z.boolean().default(false)}}, async ({id, cancel}) => textResult(await api(`/api/audio-effects/jobs/${encodeURIComponent(id)}${cancel ? '/cancel' : ''}`, cancel ? {} : undefined)));
server.registerTool('apply_speed_ramp', {description: 'Retime one video/audio clip with a saved, editable recipe, or targetDurationFrames (provide exactly one). Queues bounded local FFmpeg processing; poll get_speed_job. recipe.speed is default playback multiplier .125..8; points are ordered {frame,speed,easing:hold|linear|smoothstep} in source-relative project frames, easing belongs to the outgoing point. holds {frame,duration} freeze a source frame for additional output frames; held sound is silent. audio=preserve keeps pitch; mute removes sound. targetDurationFrames stretches the same selected source interval and scales its existing ramp. Originals and recipes remain project-owned; split retimed clips resolve back to original source. The finished edit changes only this clip duration, leaving other clips in place; inspect gaps/overlaps and coordinated audio afterward. Timeline revision changes during processing prevent commit. One undo step. Linear video ramps integrate source time, smoothstep is numerically approximated; audio ramps use short tempo slices. Slow motion repeats source frames, without optical flow.', inputSchema: applySpeedSchema.innerType().shape}, async input => textResult(await api('/api/speed/apply', input)));
server.registerTool('get_speed_job', {description: 'Read actual retiming status, progress, output duration or error. cancel=true stops processing without applying its timeline edit.', inputSchema: {id: z.string(), cancel: z.boolean().default(false)}}, async ({id, cancel}) => textResult(await api(`/api/speed/jobs/${encodeURIComponent(id)}${cancel ? '/cancel' : ''}`, cancel ? {} : undefined)));
server.registerTool('reset_clip_speed', {description: 'Restore the selected retimed clip to its retained original source interval at normal speed. One revision-checked undo step; other timeline clips stay in place.', inputSchema: resetSpeedSchema.shape}, async input => textResult(await api('/api/speed/reset', input)));
server.registerTool('export_timeline', {description: 'Export the complete editable timeline as Final Cut Pro 7 XML (xmeml5), intended for Premiere and compatible importers. Does not render a video or modify the project. Returns download URLs for XML, a compatibility/media report, and the full Framecraft JSON backup. Cuts, track placement, source trims, linked source audio, static opacity/gain and disabled tracks are exported. Overlaps split into additional tracks. Generated titles/artwork become review markers; transform curves, crop/masks, grading, custom transitions and audio envelopes require rebuilding (listed in report). Retimed/effect-processed media references preserve baked results. Files are referenced, NOT embedded; optional mediaRoot rewrites references to an absolute Windows/Linux folder holding the reported filenames. Source media must be available for metadata inspection. Review warnings and relink media in the destination editor.', inputSchema: timelineExportSchema.shape}, async input => textResult(await api('/api/timeline-export', input)));
server.registerTool('list_sound_presets', {description: 'List reusable, locally synthesized SFX recipes for impacts, whooshes, risers, clicks and transitions. Pass id to read a full recipe. Sounds are saved across projects, separately from visual presets. Inspect actual footage with inspect_video/render_frame before choosing meaningful event timestamps; this library supplies sounds, not an automatic event detector.', inputSchema: {id: z.string().optional()}}, async ({id}) => textResult(await api(`/api/sounds${id ? `/${encodeURIComponent(id)}` : ''}`)));
server.registerTool('save_sound_preset', {description: 'Save a reusable procedural SFX recipe or versioned update. Read list_sound_presets for supported layers, parameter values and existing versions. New recipes use expectedVersion=null; existing recipes require their current version. No executable code, downloaded media or external generation API. Preview before applying.', inputSchema: soundSaveSchema.shape}, async input => textResult(await api('/api/sounds/save', input)));
server.registerTool('preview_sound_preset', {description: 'Generate an isolated WAV preview from a saved SFX recipe and parameter overrides. Returns a playback URL and duration; does not modify the timeline. This does not prove that an AI has listened to the sound.', inputSchema: soundPreviewSchema.shape}, async input => textResult(await api('/api/sounds/preview', input)));
server.registerTool('apply_sound_preset', {description: 'Copy a saved SFX into the current project and place it at an exact TIMELINE FRAME on an audio track, as one undoable edit. Requires project revision and preset version. Optional trackId, durationFrames and parameter overrides. For impacts align to the inspected event frame; whooshes/risers may begin before the event. Use existing footage inspection tools and report uncertain event matches instead of inventing detections.', inputSchema: soundApplySchema.shape}, async input => textResult(await api('/api/sounds/apply', input)));
server.registerTool('edit_project', {description: 'Apply a validated atomic transaction to the live editor. Use the revision from get_project. All commands become ONE undo step. Media must first be imported. Text clips use kind=text and track=text; positions are percentages. On a revision conflict reread before retrying. Preserve unrelated user edits and locked clip positions. Use track.add/update/move/remove and clip.move-track for multiple tracks; trackId chooses the destination. track.clear clears one track. clip.update supports any visual element opacity 0..1, rotation in degrees, crop {left,top,right,bottom} percentage margins, and mask {shape:rectangle|ellipse|polygon,x,y,width,height,points,inverted,feather}. Mask x/y are center percentages; polygon points are percentage vertices; feather is in canvas pixels. Crop/mask operate in the element drawing box before transforms. Set crop/mask/keyframes to null to reset. keyframes is an object of x,y,scale,rotation,opacity arrays with ordered unique {frame,value,easing,bezier?}. frame uses the ORIGINAL CLIP ANIMATION CLOCK: timelineFrame-clip.start+(clip.motionOffset??0). Easing belongs to the outgoing key: linear,hold,ease-in,ease-out,ease-in-out,bezier; custom bezier requires {x1,y1,x2,y2} with x in0..1. Animation overrides static properties for keyed channels. Split, trim and FPS conversion preserve curves. Opacity does not mute audio. Use set_color_grade for coordinated grading; speed tools create editable retimed media.', inputSchema: {revision: z.number().int(), label: z.string().max(180), commands: z.array(commandSchema).min(1)}}, async input => textResult(await api('/api/commands', input)));
server.registerTool('inspect_clip_animation', {description: 'Read saved crop/mask/keyframe settings and evaluate position, scale, rotation and opacity at requested TIMELINE FRAMES. Returns the original animation-clock frame for each sample. This is numeric inspection; use render_frame to see the composited result.', inputSchema: {clipId: z.string(), frames: z.array(z.number().int().nonnegative()).min(1)}}, async ({clipId, frames}) => {
  const {project} = await api('/api/project') as Snapshot; const clip = project.clips.find(candidate => candidate.id === clipId);
  if(!clip || clip.kind === 'audio') throw new Error('Choose an existing visual element');
  if(frames.some(frame => frame < clip.start || frame >= clip.start + clip.duration)) throw new Error('Sample frames must be inside this clip');
  return textResult({revision: project.revision, clipId, crop: clip.crop ?? null, mask: clip.mask ?? null, keyframes: clip.keyframes ?? null, samples: frames.map(frame => ({frame, animationFrame: frame - clip.start + (clip.motionOffset ?? 0), ...visualStateAtFrame(clip, frame - clip.start)}))});
});
server.registerTool('import_media', {description: 'Copy an absolute local video/image/audio file into the requesting project media folder and read metadata/thumbnail. Compatible videos play directly. Other formats queue a background browser preview; previewSrc may not be ready yet. Returns the updated project; add a clip using edit_project. Original quality is retained for export.', inputSchema: {filePath: z.string()}}, async input => textResult(await api('/api/import-path', input)));
server.registerTool('get_media_previews', {description: 'Get background compatibility preview status/progress for this project. A ready previewSrc can be played; source inspection and export can use the original before it is ready.', inputSchema: {}}, async () => textResult(await api('/api/media/previews')));
server.registerTool('control_media_preview', {description: 'Stop background preview conversion to free CPU, or retry a cancelled/failed conversion. Does not change the original or timeline.', inputSchema: {assetId: z.string(), action: z.enum(['cancel', 'retry'])}}, async ({assetId, action}) => textResult(await api(`/api/media/${encodeURIComponent(assetId)}/preview`, {action})));
server.registerTool('undo_redo', {description: 'Undo or redo one transaction, including manual UI edits. Get current revision first.', inputSchema: {direction: z.enum(['undo', 'redo']), revision: z.number().int()}}, async ({direction, revision}) => textResult(await api(`/api/history/${direction}`, {revision})));
server.registerTool('render_frame', {description: 'Render and SEE a composited PNG frame from the current project. Uses the same composition as preview/export. Returns an image when ready, or a job ID to poll with get_render. Use before/during/after transitions to inspect appearance. Frame must be inside project duration.', inputSchema: {frame: z.number().int().nonnegative()}}, async ({frame}) => {
  let job: RenderJob = await api('/api/render', {kind: 'frame', frame});
  const deadline = Date.now() + 45_000;
  while(Date.now() < deadline && ['queued', 'rendering'].includes(job.status)) {await new Promise(resolve => setTimeout(resolve, 700)); job = await api(`/api/render/${job.id}`);}
  return renderResult(job);
});
server.registerTool('get_export_encoders', {description: 'Detect working AMD (VA-API on Linux, AMF on Windows) and NVIDIA NVENC encoders for a codec. Includes unavailable reasons. Detection uses one synthetic frame, never project media.', inputSchema: {codec: z.enum(codecNames).default('h264')}}, async ({codec}) => textResult(await api(`/api/render/encoders?codec=${encodeURIComponent(codec)}`)));
server.registerTool('export_video', {description: 'Queue an export of a frozen project revision. Specify resolution, fps, codec, bitrate/quality, audio and time range, or use project defaults. encoder=auto prefers a working GPU with visible CPU fallback; amd/nvidia require the selected GPU; cpu forces software. Quality uses CRF on CPU and CQ/QP on GPU. Poll get_render for actual encoder, progress and output. Changing output fps preserves timing; fit controls aspect ratio.', inputSchema: {settings: exportSettingsSchema.optional(), revision: z.number().int().optional()}}, async input => textResult(await api('/api/render', {kind: 'video', ...input})));
server.registerTool('get_render', {description: 'Get export/frame status. Completed frame jobs include the PNG image for visual inspection.', inputSchema: {id: z.string()}}, async ({id}) => renderResult(await api(`/api/render/${id}`)));
server.registerTool('get_transcript', {description: 'Read word timestamps in SOURCE SECONDS for one imported asset, or list available transcripts when assetId is omitted. A null transcript means transcription has not been run.', inputSchema: {assetId: z.string().optional()}}, async ({assetId}) => textResult(await api(`/api/analysis/transcripts${assetId ? `/${encodeURIComponent(assetId)}` : ''}`)));
server.registerTool('transcribe_media', {description: 'Queue real local Whisper speech recognition. First use downloads the model. Pass the current transcript revision when replacing one, otherwise null. Returns an analysis job ID; poll get_analysis. Does not change the timeline.', inputSchema: {assetId: z.string(), language: z.enum(['auto', 'french', 'english']).default('auto'), revision: z.number().int().nonnegative().nullable().default(null)}}, async input => textResult(await api('/api/analysis/transcribe', input)));
server.registerTool('get_analysis', {description: 'Read a queued local analysis job, including errors, search results or a first-cut proposal. Omit id to list jobs. Jobs are discarded on server restart; transcripts persist.', inputSchema: {id: z.string().optional()}}, async ({id}) => textResult(await api(`/api/analysis/jobs${id ? `/${encodeURIComponent(id)}` : ''}`)));
server.registerTool('cancel_analysis', {description: 'Cancel a queued or running local analysis without changing the timeline.', inputSchema: {id: z.string()}}, async ({id}) => textResult(await api(`/api/analysis/jobs/${encodeURIComponent(id)}/cancel`, {})));
server.registerTool('correct_transcript', {description: 'Save corrected word text and source-second timestamps. Get the transcript first and retain word IDs and timings unless a correction is needed. Pass its revision (null to import the first transcript). Does not regenerate captions automatically.', inputSchema: {assetId: z.string(), revision: z.number().int().nonnegative().nullable(), language: z.string().max(40).default('manual'), words: z.array(transcriptWordSchema).max(100000)}}, async ({assetId, ...input}) => textResult(await api(`/api/analysis/transcripts/${encodeURIComponent(assetId)}`, input)));
server.registerTool('search_footage', {description: 'Queue local multilingual semantic search over spoken transcript passages; untranscribed assets match by filename. Does not analyze imagery. Poll get_analysis for source-second ranges and relevance scores. Add an excerpt with edit_project using frames at the current project fps.', inputSchema: {query: z.string().min(1).max(500)}}, async input => textResult(await api('/api/analysis/search', input)));
server.registerTool('cut_transcript_words', {description: 'Remove selected source words from one timeline clip and ripple ALL tracks to retain synchronization. Default apply=false returns exact ranges and affected clip count for review. apply=true commits one undoable transaction. Get project and transcript revisions first.', inputSchema: {revision: z.number().int().nonnegative(), transcriptRevision: z.number().int().nonnegative(), clipId: z.string(), wordIds: z.array(z.string()).min(1), apply: z.boolean().default(false)}}, async input => textResult(await api('/api/analysis/cut', input)));
server.registerTool('generate_captions', {description: 'Create word-timed text clips from a source transcript for one timeline clip, replacing its previously generated captions in one undo step. Styles: clean, highlight, boxed. Download all timeline captions from /api/analysis/subtitles/srt or /vtt. Captions are separate timeline layers; regenerate after manually moving/trimming the parent.', inputSchema: {revision: z.number().int().nonnegative(), transcriptRevision: z.number().int().nonnegative(), clipId: z.string(), options: captionOptionsSchema.default({})}}, async input => textResult(await api('/api/analysis/captions', input)));
server.registerTool('propose_first_cut', {description: 'Queue a reviewable first-cut proposal. Selects spoken passages by topic, preserves source order and respects a target duration. Without transcripts uses opening shots. Poll get_analysis, review/reorder shots, then apply_first_cut. Does not change timeline.', inputSchema: {assetIds: z.array(z.string()).min(1).max(100), seconds: z.number().min(5).max(3600), topic: z.string().max(500).default('')}}, async input => textResult(await api('/api/analysis/roughcut', input)));
server.registerTool('apply_first_cut', {description: 'Apply reviewed first-cut shots in order, using integer SOURCE FRAMES at the current project fps. Append or replace timeline clips in one undo step; imported media are preserved. Use the project revision from the proposal.', inputSchema: {revision: z.number().int().nonnegative(), mode: z.enum(['append', 'replace']), shots: z.array(z.object({assetId: z.string(), sourceStart: z.number().int().nonnegative(), duration: z.number().int().positive()})).min(1).max(1000), title: z.string().max(120).default(''), addTitle: z.boolean().default(false)}}, async input => textResult(await api('/api/analysis/roughcut/apply', input)));
async function renderResult(job: RenderJob) {
  if(job.status === 'done' && job.kind === 'frame' && job.url) {
    const response = await fetch(base + job.url); if(!response.ok) throw new Error('Could not retrieve frame');
    return {content: [{type: 'text' as const, text: JSON.stringify(job)}, {type: 'image' as const, data: Buffer.from(await response.arrayBuffer()).toString('base64'), mimeType: 'image/png'}]};
  }
  return textResult({...job, ...(job.url ? {downloadUrl: base + job.url} : {})});
}
await server.connect(new StdioServerTransport());
