import type {Clip} from '../../../shared/project';
import {useEditor} from '../../stores/editor-store';
import {Field, NumberField} from '../atoms/Field';
import {PropertySection} from '../atoms/PropertySection';
export function OverlayProperties({clip, patch}: {clip: Clip; patch: (value: Partial<Clip>) => void}) {
  const fps = useEditor(s => s.snapshot?.project.fps ?? 30);
  const annotation = clip.annotation; const zoom = clip.zoom;
  return <>
    {annotation && <PropertySection title="Callout shape"><Field label="Shape"><select aria-label="Annotation shape" value={annotation.shape} onChange={e => patch({annotation: {...annotation, shape: e.target.value as typeof annotation.shape}})}><option value="arrow">Arrow</option><option value="box">Frame</option><option value="circle">Circle</option></select></Field><div className="field-row"><NumberField label="Width" value={annotation.width} min={2} max={100} suffix="%" onCommit={width => patch({annotation: {...annotation, width}})}/><NumberField label="Height" value={annotation.height} min={2} max={100} suffix="%" onCommit={height => patch({annotation: {...annotation, height}})}/></div><div className="field-row"><NumberField label="Rotation" value={annotation.rotation} min={-180} max={180} suffix="°" onCommit={rotation => patch({annotation: {...annotation, rotation}})}/><NumberField label="Stroke" value={annotation.stroke} min={.1} max={300} suffix="px" onCommit={stroke => patch({annotation: {...annotation, stroke}})}/></div><Field label="Annotation color"><input type="color" aria-label="Annotation color" value={clip.color} onChange={e => patch({color: e.target.value})}/></Field></PropertySection>}
    {zoom && <PropertySection title="Focus zoom"><button className="property-inline-action" onClick={() => patch({zoom: null})}>Remove focus zoom</button><div className="field-row"><NumberField label="Zoom from" value={zoom.from} min={1} max={4} step={.1} suffix="×" onCommit={from => patch({zoom: {...zoom, from}})}/><NumberField label="Zoom to" value={zoom.to} min={1} max={4} step={.1} suffix="×" onCommit={to => patch({zoom: {...zoom, to}})}/></div><div className="field-row"><NumberField label="Focus X" value={zoom.x} max={100} suffix="%" onCommit={x => patch({zoom: {...zoom, x}})}/><NumberField label="Focus Y" value={zoom.y} max={100} suffix="%" onCommit={y => patch({zoom: {...zoom, y}})}/></div><div className="field-row"><NumberField label="Zoom start" value={zoom.start / fps} max={(zoom.end - 1) / fps} step={1 / fps} suffix="s" onCommit={start => patch({zoom: {...zoom, start: Math.round(start * fps)}, motionOffset: 0})}/><NumberField label="Zoom end" value={zoom.end / fps} min={(zoom.start + 1) / fps} step={1 / fps} suffix="s" onCommit={end => patch({zoom: {...zoom, end: Math.round(end * fps)}, motionOffset: 0})}/></div></PropertySection>}
    {clip.caption && <PropertySection title="Captions"><Field label="Caption style"><select aria-label="Caption style" value={clip.caption.style} onChange={e => patch({caption: {...clip.caption!, style: e.target.value as NonNullable<Clip['caption']>['style']}})}><option value="clean">Clean</option><option value="highlight">Word highlight</option><option value="boxed">Boxed</option></select></Field><Field label="Highlight color"><input type="color" aria-label="Highlight color" value={clip.caption.highlightColor} onChange={e => patch({caption: {...clip.caption!, highlightColor: e.target.value}})}/></Field><p className="field-help">Edit words in Tools → Transcript & captions, then regenerate. Captions are separate layers: regenerate after moving or trimming their source clip.</p><button onClick={() => patch({caption: null})}>Convert to editable plain text</button></PropertySection>}
  </>;
}
