import {useCallback, useRef, useState} from 'react';
import {ChevronDown, Copy, Eraser, FilePlus2, FolderOpen, Pencil, ShieldCheck} from 'lucide-react';
import {useDismissableLayer} from '../../hooks/useDismissableLayer';
export function ProjectMenu({name, disabled, onNew, onOpen, onCopy, onRename, onClear, onCare}: {name: string; disabled: boolean; onNew: () => void; onOpen: () => void; onCopy: () => void; onRename: () => void; onClear: () => void; onCare: () => void}) {
  const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null); const close = useCallback(() => setOpen(false), []);
  useDismissableLayer(ref, open, close);
  const options = [{label: 'New project', detail: 'Start with a blank canvas', icon: FilePlus2, action: onNew}, {label: 'Open project', detail: 'Browse your saved projects', icon: FolderOpen, action: onOpen}, {label: 'Save as', detail: 'Continue in a separate copy', icon: Copy, action: onCopy}, {label: 'Project safety & portability', detail: 'Recovery, missing files and portable projects', icon: ShieldCheck, action: onCare}, {label: 'Rename project', icon: Pencil, action: onRename}, {label: 'Start a blank timeline', detail: 'Clear this project’s timeline', icon: Eraser, action: onClear}];
  return <div className="project-menu" ref={ref}><button className="project-menu__trigger" aria-label="Project menu" aria-expanded={open} disabled={disabled} onClick={() => setOpen(!open)}><span>{name}</span><ChevronDown size={13}/></button>{open && <div className="project-menu__panel"><p>YOUR WORKSPACE</p>{options.map(({label, detail, icon: Icon, action}) => <button key={label} disabled={disabled} onClick={() => {close(); action();}}><Icon size={16}/><span>{label}{detail && <small>{detail}</small>}</span></button>)}<div className="project-menu__saved">Changes save automatically</div></div>}</div>;
}
