import {presetDefinitionSchema, type PresetDefinition} from './asset-presets';
import {presentationStarters} from './presets/presentation-starters';
const accent = {key: 'accent', label: 'Accent color', type: 'color', default: '#bc8cff'};
const title = {key: 'title', label: 'Title', type: 'text', default: 'A NEW CHAPTER'};
const fade = {keyframes: [{at: 0, value: 0}, {at: .15, value: 1}, {at: .85, value: 1}, {at: 1, value: 0}]};
const rise = {keyframes: [{at: 0, value: 62}, {at: .2, value: 50}]};
const definition = (value: unknown) => presetDefinitionSchema.parse(value);
export const legacyPresetStarters: {id: string; definition: PresetDefinition}[] = [
  {id: 'purple-glitch', definition: definition({schemaVersion: 1, name: 'Purple Glitch', description: 'A staggered block reveal with animated purple bands.', category: 'transition', tags: ['glitch', 'gaming'], duration: .8, parameters: [accent, {key: 'intensity', label: 'Band height', type: 'number', min: 1, max: 24, step: 1, default: 8}], reveal: {type: 'blocks', steps: 14}, layers: [18, 45, 73].map((y, i) => ({id: `band-${i}`, type: 'rect', x: {keyframes: [{at: 0, value: -60}, {at: .5, value: 50}, {at: 1, value: 160}]}, y, width: 120, height: {param: 'intensity'}, fill: {param: 'accent'}, opacity: {keyframes: [{at: 0, value: 0}, {at: .3, value: .9}, {at: .7, value: .9}, {at: 1, value: 0}]}}))})},
  {id: 'chapter-title', definition: definition({schemaVersion: 1, name: 'Chapter Title', description: 'An animated title and accent rule for a new chapter.', category: 'title', tags: ['title', 'devlog'], duration: 4, parameters: [title, accent], layers: [{id: 'rule', type: 'rect', x: 50, y: 61, width: {keyframes: [{at: 0, value: 0}, {at: .25, value: 22}]}, height: .6, fill: {param: 'accent'}, opacity: fade}, {id: 'heading', type: 'text', text: {param: 'title'}, y: rise, fontSize: 9, opacity: fade}]})},
  {id: 'lower-third', definition: definition({schemaVersion: 1, name: 'Developer Lower Third', description: 'A nameplate with editable name, role and accent.', category: 'lower-third', duration: 5, parameters: [{...title, default: 'YOUR NAME'}, {key: 'subtitle', label: 'Subtitle', type: 'text', default: 'Developer · Devlog 001'}, accent], layers: [{id: 'panel', type: 'rect', x: 28, y: 80, width: 44, height: 19, radius: 1, fill: '#12151e', opacity: fade}, {id: 'accent', type: 'rect', x: 6.5, y: 80, width: .6, height: 19, fill: {param: 'accent'}, opacity: fade}, {id: 'name', type: 'text', x: 30, y: 76, width: 42, height: 8, text: {param: 'title'}, fontSize: 5, align: 'left', opacity: fade}, {id: 'role', type: 'text', x: 30, y: 84, width: 42, height: 6, text: {param: 'subtitle'}, fill: {param: 'accent'}, fontSize: 2.8, weight: '400', align: 'left', opacity: fade}]})},
  {id: 'orbit-background', definition: definition({schemaVersion: 1, name: 'Orbit Background', description: 'Slow geometric motion for chapter cards and intros.', category: 'background', tags: ['abstract', 'background'], duration: 6, parameters: [accent, {key: 'background', label: 'Background color', type: 'color', default: '#10151d'}], layers: [{id: 'base', type: 'rect', width: 100, height: 100, fill: {param: 'background'}}, ...[0, 1, 2].map(i => ({id: `orb-${i}`, type: 'ellipse', x: {keyframes: [{at: 0, value: 10 + i * 30}, {at: 1, value: 40 + i * 25}]}, y: 20 + i * 30, width: 45, height: 70, fill: {param: 'accent'}, opacity: .1 + i * .07}))]})},
  {id: 'focus-callout', definition: definition({schemaVersion: 1, name: 'Focus Callout', description: 'An animated frame with an editable label.', category: 'overlay', duration: 4, parameters: [accent, {...title, default: 'LOOK HERE'}], layers: [{id: 'frame', type: 'rect', width: 40, height: 42, fill: '#12151e', opacity: {keyframes: [{at: 0, value: 0}, {at: .2, value: .85}, {at: .85, value: .85}, {at: 1, value: 0}]}, stroke: {param: 'accent'}, strokeWidth: .4, scale: {keyframes: [{at: 0, value: .7}, {at: .2, value: 1}]}}, {id: 'label', type: 'text', text: {param: 'title'}, y: 50, fontSize: 4, fill: {param: 'accent'}, opacity: fade}]})},
  ...(['intro', 'outro'] as const).map(category => ({id: `devlog-${category}`, definition: definition({schemaVersion: 1, name: category === 'intro' ? 'Devlog Intro' : 'Devlog Outro', description: 'A complete animated card with a title and subtitle.', category, duration: 5, parameters: [accent, {...title, default: category === 'intro' ? 'BUILDING SOMETHING NEW' : 'THANKS FOR WATCHING'}, {key: 'subtitle', label: 'Subtitle', type: 'text', default: category === 'intro' ? 'DEVLOG / 001' : 'SEE YOU IN THE NEXT DEVLOG'}], layers: [{id: 'base', type: 'rect', width: 100, height: 100, fill: '#10151d'}, {id: 'orb', type: 'ellipse', x: 82, y: 20, width: 55, height: 90, fill: {param: 'accent'}, opacity: .2, scale: {keyframes: [{at: 0, value: .7}, {at: 1, value: 1.2}]}}, {id: 'title', type: 'text', text: {param: 'title'}, fontSize: 7, y: rise, opacity: fade}, {id: 'subtitle', type: 'text', text: {param: 'subtitle'}, fontSize: 2.5, y: 64, fill: {param: 'accent'}, opacity: fade}]})})),
];
export const presetStarters = [...legacyPresetStarters, ...presentationStarters];
