import {agentProviderNames, cliAgentPresets, isCliAgent} from '../../../shared/agent-providers';
import {Check, Clipboard, Terminal} from 'lucide-react';
import {useState} from 'react';
import type {ServerStatus} from '../../services/editor-api';
import {useAgent} from '../../stores/agent-store';
import {Button} from '../atoms/Button';

export function AgentConnectionPanel({status, error}: {status: ServerStatus | null; error: string | null}) {
  const [copied, setCopied] = useState(false); const [copyError, setCopyError] = useState(false);
  const session = useAgent(s => s.session);
  if(session.provider === 'ollama') return <div className="agent-connection-panel"><h4>Ollama on your network</h4><p>Server: <code>{session.providerSettings?.ollamaUrl}</code></p><p>Load models, choose a tool-capable model, then start Ollama from Chat. Framecraft connects its MCP tools automatically.</p><p>For Automatic Cuts and visual review, select a model with vision support. No Codex CLI or cloud account is used by this provider.</p><p>Ollama must listen on a network interface reachable from the editor host. For local speech recognition, keep the composer’s Speech recognition setting on Local.</p>{error && <p role="alert">{error}</p>}</div>;
  if(isCliAgent(session.provider)) return <div className="agent-connection-panel"><h4>{agentProviderNames[session.provider]} in Framecraft</h4><p>{cliAgentPresets[session.provider].setup}</p><p>Save your executable and arguments in Settings, then start the agent from Chat. Framecraft passes its MCP bridge to the CLI when it creates the session. Timeline editing, inspection, export and reusable asset tools use the same server as Codex.</p><p>Replies, tool calls and permission requests stream into this conversation. Native file and command tools are handled by the CLI itself. Login remains in its own terminal interface.</p><p>Browser reloads keep the running conversation. Reconnecting within this editor run resumes it only if the agent supports session loading; otherwise it starts a new conversation. Restarting the editor starts a new CLI chat.</p>{session.threadId && <p>Session: <code>{session.threadId}</code></p>}{error && <p role="alert">{error}</p>}</div>;
  const command = `codex mcp add framecraft -- node "${status?.rootDir.replaceAll('\\', '/') || '<project-folder>'}/scripts/mcp.mjs"`;
  return <div className="agent-connection-panel"><div className="codex-step"><Terminal size={16}/><div><h4>Built into your editor</h4><p>Start Codex from Chat. Framecraft connects the timeline tools automatically and uses your existing Codex sign-in. Send your editing requests here.</p></div></div>
    {error && <p className="connection-error" role="alert">{error}</p>}
    <p className="field-help">{status?.agentConnections.length || 0} active timeline connection(s). The indicator tracks initialized MCP sessions, including those in external terminals.</p>
    {session.threadId && <p className="field-help">Chat session: <code>{session.threadId}</code>. Your conversation reconnects after a page reload. After restarting Framecraft, click Start Codex to resume it.</p>}
    <details className="agent-manual"><summary>Use an external Codex terminal</summary><p className="field-help">Register once at your shell prompt, then run <code>codex</code> in the project folder. Keep Framecraft running.</p><code className="connection-command">{command}</code><Button className="copy-command" disabled={!status} icon={copied ? <Check size={14}/> : <Clipboard size={14}/>} onClick={() => {if(!navigator.clipboard) {setCopyError(true); return;} void navigator.clipboard.writeText(command).then(() => {setCopied(true); setCopyError(false);}).catch(() => setCopyError(true));}}>{copied ? 'Copied' : 'Copy registration command'}</Button>{copyError && <p className="field-help">Select and copy the command above.</p>}<p className="field-help">Type <code>/mcp</code> inside Codex to inspect tools and startup errors. External terminal conversations stay in that terminal.</p></details>
  </div>;
}
