import {useEffect, useState} from 'react';
import {ArrowDown, ArrowUp} from 'lucide-react';
import {projectTracks, trackClips} from '../../../shared/tracks';
import {useEditor} from '../../stores/editor-store';
import {Dialog} from '../atoms/Dialog';
import {Field} from '../atoms/Field';
import {Button} from '../atoms/Button';
export function TrackSettingsDialog({id, onClose}: {id: string; onClose: () => void}) {
  const project = useEditor(s => s.snapshot?.project); const busy = useEditor(s => s.busy); const tracks = project ? projectTracks(project) : []; const track = tracks.find(t => t.id === id);
  const [name, setName] = useState(track?.name ?? ''); useEffect(() => setName(track?.name ?? ''), [track?.name]);
  if(!track || !project) return null; const count = trackClips(project, id).length; const index = tracks.findIndex(t => t.id === id);
  const update = (patch: Partial<Pick<typeof track, 'name' | 'muted' | 'hidden'>>) => void useEditor.getState().execute([{type: 'track.update', id, patch}], `Updated ${track.name}`);
  return <Dialog title="Track settings" onClose={onClose}><div className="settings-form"><Field label="Track name"><input aria-label="Track name" maxLength={60} value={name} onChange={event => setName(event.target.value)} onBlur={() => {if(name.trim() && name.trim() !== track.name) update({name: name.trim()});}}/></Field><p className="settings-description">{count} clips · {track.type === 'visual' ? 'Video / images / graphics' : track.type === 'text' ? 'Text / graphics' : 'Audio'}. Higher tracks appear above lower tracks in preview and export.</p><div className="settings-grid"><Button icon={<ArrowUp size={14}/>} disabled={busy || index === 0} onClick={() => void useEditor.getState().execute([{type: 'track.move', id, direction: 'up'}], `Moved ${track.name} up`)}>Move track up</Button><Button icon={<ArrowDown size={14}/>} disabled={busy || index === tracks.length - 1} onClick={() => void useEditor.getState().execute([{type: 'track.move', id, direction: 'down'}], `Moved ${track.name} down`)}>Move track down</Button></div>{track.type !== 'text' && <label className="settings-checkbox"><input type="checkbox" aria-label="Mute track" checked={track.muted} disabled={busy} onChange={event => update({muted: event.target.checked})}/>Mute track audio</label>}{track.type !== 'audio' && <label className="settings-checkbox"><input type="checkbox" aria-label="Hide track" checked={track.hidden} disabled={busy} onChange={event => update({hidden: event.target.checked})}/>Hide track, including its sound</label>}<p className="field-help">{count ? 'Move or remove its clips before deleting this track.' : 'This empty track can be removed. Undo restores it.'}</p><div className="settings-actions"><Button disabled={busy || count > 0} onClick={() => {void useEditor.getState().execute([{type: 'track.remove', id}], `Removed ${track.name}`).then(ok => {if(ok) onClose();});}}>Remove empty track</Button><Button variant="primary" onClick={onClose}>Done</Button></div></div></Dialog>;
}
